### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rainbowatcher** [rainbowatcher/wasmup#1]
- [ ] detect wasm-bindgen version
- [x] check wasm-bindgen js output in unit test
- [x] show spinner when build rust
